Repository glimmerjs/glimmer.js, pull requests merged in 2019-02, with the labels that each got.

#172 Upgrade Ember CLI to 3.7.1
  package.json
  yarn.lock
Labels: internal

#173 Include SimpleDOM types in @glimmer/application dependencies
  packages/@glimmer/application/package.json
Labels: bug

#174 Better setPropertyDidChange error message
  packages/@glimmer/component/index.ts
  packages/@glimmer/component/src/deprecations.ts
  yarn.lock
Labels: enhancement

#169 Fixed broken tests from glimmer-vm update; fix passing of dynamicScope
  packages/@glimmer/application/src/loaders/bytecode/loader.ts
Labels: internal
